M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Sun 24 Nov 2024 08:43:36 GMT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-24T08:43:36+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.3765Y-4.4156
X5.5675Y-4.4156
T2
X5.3647Y-4.5349
X5.5793Y-4.5349
M30
